### ISSUE TITLE
add Content Security Policy manager

### ISSUE THREAD

**Issue by ccamensuli** [nodefony/nodefony#55]

**Comment by matigda** [comment]
I didn't want to create another topic for this so I will leave my comment here.

For the backend tech, where the security is absolutely everything, a project like this would be 1000x more appealing if were written in typescript. But that's just my opinion :)

**Comment by ccamensuli** [comment]
why typescript ? 

what is the fundamental reason ?

**Comment by matigda** [comment]
Security. Backend has been my "area of interest" and I was always scared of writting it in JS. With typescript it's different.
I know you CAN write good backend in JS, I know. But I would rather use best tools there are to write it. And pure JS is not in this group.

**Comment by ccamensuli** [comment]
Good , 
nodefony is Node.js Project .

All the framework can not be written in typescript (also for  transcoding reasons).

But I will think about the feasibility of coding a bundle (controllers services ...) in typescript.

Thanks for the interest in the project
